name: TruffleHog Secrets Scan
on:
  push:
    branches: [main]
  pull_request:

jobs:
  trufflehog:
    name: TruffleHog scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@36d680a074f34a8ec9ae32614ace45c34ec820c5
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified --fail --no-update
